apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deploy.yml
- backend/service.yml
- frontend/deploy.yml
- frontend/service.yml


images:
- name: 221719046810.dkr.ecr.us-east-1.amazonaws.com/workshop-devops/production/backend
  newName: 221719046810.dkr.ecr.us-east-1.amazonaws.com/workshop-devops/production/backend
  newTag: f6b128fba49bff305e0968cecca0780562ea6c91
- name: 221719046810.dkr.ecr.us-east-1.amazonaws.com/workshop-devops/production/frontend
  newName: 221719046810.dkr.ecr.us-east-1.amazonaws.com/workshop-devops/production/frontend
  newTag: v1.0
